resources:

  - name: ion-app-service
    type: git
    source:
      uri: https://github.com/ssadcloud/ion.git
      branch: master

  - name: ion-app-service-docker-repository
    type: docker-image
    source:
      email: kumar24@gmail.com
      username: ssadcloud
      password: 123456789
      repository: ssadcloud/dbeta

jobs:
  - name: test
    public: true
    plan:
      - get: ion-app-service
        trigger: true
      - task: mvn-test
        file: "ion-app-service/configuration/tasks/task-test.yml"

  - name: package
    public: true
    serial: true
    plan:
      - get: ion-app-service
        trigger: true
        passed: [test]

      - task: mvn-package
        file: "ion-app-service/configuration/tasks/task-package.yml"

      - put: ion-app-service-docker-repository
        params:
          build: ion-app-service-out
