---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.6.0-jdk-8-alpine
inputs:
  - name: ion-app-service
run:
  path: "mvn"
  args:
    - -f
    - ion-app-service/pom.xml
    - clean
    - test
